package:
  name: chemps2
  version: "1.5"

source:
  #git_url: git@github.com:SebWouters/CheMPS2.git
  #git_tag: "1.5"
  path: /theoryfs2/ds/loriab/chem/condatrial/lab-CheMPS2


build:
  #string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_DESCRIBE_HASH', 'GIT_STUB') }}
  number: 4
  binary_relocation: true
  #binary_has_prefix_files:
  #  - bin/psi4
  #has_prefix_files:
  #  - share/psi/scripts/setenv.py

requirements:
  build:
    - cmake >=2.8.11
    - hdf5
    - gsl
  run:
    - hdf5
    - gsl

about:
  home: https://github.com/SebWouters/CheMPS2#chemps2-a-spin-adapted-implementation-of-dmrg-for-ab-initio-quantum-chemistry
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "a spin-adapted implementation of DMRG for ab initio quantum chemistry"
  #readme: README.rst

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../psi4mangle/psi4
#build/number: 1
#build/string: abc
